import time, hashlib
import requests
import json
from django.http import JsonResponse

# Your API Key and secret
apiKey = "pe6ud6vswhta6a49epk356kz"
Secret = "t7WVC5ukk7"

# Signature is generated by SHA256 (Api-Key + Secret + Timestamp (in seconds))
sigStr = "%s%s%d" % (apiKey, Secret, int(time.time()))
signature = hashlib.sha256(sigStr).hexdigest()


def call(endpoint, params=None):

    # Create http request and add headers
    headers = {'X-Signature': signature, 'Api-Key': apiKey, 'Accept': 'application/json', 'Content-Type': 'application/json'}

    # Reading response and print-out
    response = requests.post(endpoint, json=params, headers=headers)

    return response.content


def avail_destination(destination_code):
    params = {
      'filters': [
            {
                'searchFilterItems': [
                    {'type': 'destination', 'value': destination_code}
                ]

            }
      ],
      'from': '2018-03-28',
      'to': '2018-03-30',
      'language': 'en',
      'pagination': {
        'itemsPerPage': 10,
        'page': 1
      },
      'order': 'DEFAULT'
    }

    return call("https://api.test.hotelbeds.com/activity-api/3.0/activities", params)
